In [3]:
import tensorflow as tf

In [4]:
# tf.placeholder : 입력값을 받는 변수
# None : 크기가 정해지지 않음
X = tf.placeholder(tf.float32, [None, 3])
print(X)

In [5]:
# 두번째 차원의 요소 갯수 = 3
x_data = [[1, 2, 3], [4, 5, 6]]

In [9]:
# tf.Variable : 그래프를 계산하면서 최적화 할 변수들. 이 값이 신경망을 좌우하는 값이다.
# tf.random_normal : 각 변수들의 초기값을 정규분포 랜덤 값으로 초기화한다.

# [[-0.14479451 -0.50265551] [-2.46794224 0.56639165] [1.38471031 -0.59352636]]
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [10]:
# tf.matmul : mat* 행렬 계산 관련 함수
expr = tf.matmul(X, W) + b

In [11]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[  1.08551502e+00  -1.23015733e-03]
 [  4.47578728e-01  -1.10272551e+00]
 [  1.63118184e+00  -8.71848643e-01]]
=== b ===
[[-2.26712871]
 [ 0.03953916]]
=== expr ===
[[  4.60708904  -7.08935642]
 [ 16.40658379 -10.71010017]]
